//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjmeraPracticalAssessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookMaster
    {
        public long BookID { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
